(package "sideline-color"
         "0.1.0"
         "Show color information with sideline")

(website-url "https://github.com/emacs-sideline/sideline-color")
(keywords "convenience" "color")

(package-file "sideline-color.el")

(source "gnu")
(source "melpa")
(source "jcs-elpa")

(depends-on "emacs" "27.1")
(depends-on "sideline")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
